### ISSUE TITLE
Kernel module compilation fails on 3.x kernels.

### ISSUE THREAD

**Issue by peci1** [intel-ros/librealsense-release#1]
I've tried installing ros-indigo-librealsense on Ubuntu Trusty.

The dkms patching ov uvcvideo.ko fails on 3.13 and 3.19 kernels, whereas it is successful on 4.2 and 4.4. Shouldn't there be a dependency of this library on the 4.x+ kernels? Or the other way round, if there is a way to fix the build on 3.x kernels, it would be even better ;)

**Comment by mdhorn** [comment]
This repository is for releasing librealsense; not the correct place to report. I'll be disabling Issues on this repo.
Use https://github.com/intel-ros/realsense

Librealsense can work for some camera using a 3.19.x or higher kernel, but we are only support 4.x kernels due to all of the known issues and limitations. Librealsense project only supports the 4.x kernels as well.

Once ubunutu 14.04.4 was released with a 4.2 kernel and 14.04.5 with a 4.4 kernel, support for the older kernel was lower priority.
https://wiki.ubuntu.com/Kernel/LTSEnablementStack

If you really need the 3.19 kernel, you should be able to patch it manually -- but there are several limitations.
